---
abstract: 'General purpose, MongoDB-style query and update language'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MQUL
requires:
  Carp: 0
  Data::Compare: 0
  Data::Types: 0
  DateTime::Format::W3CDTF: 0
  Exporter: 0
  Scalar::Util: 0
  Try::Tiny: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/ido50/MQUL
  repository: https://github.com/ido50/MQUL.git
version: 0.004
